### ISSUE TITLE
List.xml is remapping to ringtones instead of Desktops

### ISSUE THREAD

**Issue by rofferman** [dkgroot/provision_sccp#4]
[provision.log](https://github.com/dkgroot/provision_sccp/files/3821250/provision.log)
I have a strange issue where List.xml is rewriting to ringtones instead of Desktops in tftpboot

I followed the install instructions that are here https://github.com/PhantomVl/sccp_manager/wiki/Instal-on-CentOS-7

Everything else seems to working except for the Desktops

**Comment by dkgroot** [comment]
@rofferman I was not aware Alexander was using some of this code (already).  :-)

Note if you are using java phones (for desktops that makes sense) and have a webserver listening on 6970, the phones will be pulling via http

HTTP:6970
===
Apache
---
The rewrite rules for apache http are coming from [tftpboot/index.php](https://github.com/dkgroot/provision_sccp/blob/master/tftpboot/index.php), so we need to check these rules to make sure this is correct.
At a quick glance there does not seem to be a matching rule for List.xml -> Desktop. TBH i have not written this file, it came from Alexander (PhantomVl) so i will need to have a good look tomorrow to see what it is intending to do.
Maybe you can switch $print_debug='on' in the /tftpboot/index.cnf file so we get some detailed logging,

Nginx
---
For nginx we use the same rewrite.rules that are used below (continue in the TFTP block).

TFTP:69
===
When i look at the instructions, the rewrite rules are coming from :`
/var/www/html/admin/modules/sccp_manager/contrib/rewrite.rules (ie: [rewrite.rules on github](https://github.com/PhantomVl/sccp_manager/blob/extension_mobility/contrib/rewrite.rules)) Line 204
So they are part of the sccp_manager install. Sounds a little like i am redirecting you there (which is not what i want to do). 

It looks like lines 199-201 might be matching before the Desktop ones (although i don't see how exactly). Can you remark them out, to see if that is the case ?

You can give the rewrite.rules from provision_sccp/etc/tftpd-hpa/ a try, to see if that resolves the issue. Although it looks like an identical copy.

**Comment by dkgroot** [comment]
@PhantomVl 
- We should really use one directory (mine or yours, don't care) to get the files from, and copy them in one/two commands,
- We should only use one rewrite.rules file for all three servers. The regexes should be compatible with apache as well (AFAIK), i just don't have apache so it's a little hard to experiment.
- If provision_sccp is supposed to be the new default for sccp provisioning, we need to allocate a little time to improve docs and integration and move the repo to https://github.com/chan-sccp when it is ready.

**Comment by rofferman** [comment]
I tried commenting those lines out and it still is trying to pull from ringtones dir.
I will keep looking thru it and see if I can find anything 
I will turn on the debug settings and if I see anything I strange i will post it back here

**Comment by dkgroot** [comment]
Please re-read what i wrote... i changed the content in the meantime :-)... Based on the last line, you are using apache + index.php + index.cfg i assume. 

In that case, remarking stuff out in the rewrite.rules is not going to do anything (at the moment) the index.php is a stand alone rewriter for apache only at the moment. And as far as i can tell it does not contain rules for List.xml. Then again, don't devices pull the desktop list.xml from a subdirectory already (forgot) ?

**Comment by rofferman** [comment]
Yes they should pull images from the Desktops directory by default. 
but something in the rewrite is messing with List.xml

and yes I am using apache

**Comment by dkgroot** [comment]
BTW: I am really happy someone is starting to use the stuff from provision_sccp. I was sort started as just a storage repo for firmware and then grew to be a little experiment, to see if we could do this. It never really got much attention / traction though
(I use it on my servers though with tftp/nginx).

**Comment by dkgroot** [comment]
Ooh that should making debugging a lot easier then, you can just pull that same url from your browser, make a small change and refresh until it works (right ?).

**Comment by rofferman** [comment]
yes i really like how is organizes all the firmware and files in tftpboot

and yes i should be able to make small changes and refresh

**Comment by dkgroot** [comment]
> yes i really like how is organizes all the firmware and files in tftpboot

I really hated the old Cisco way, with everything in one directory. It makes sense from a CUCM perspective where all the files are generated anyway. But for chan_sccp it's just ugly.

> and yes i should be able to make small changes and refresh

If you need any help git me a shout on [chat](https://gitter.im/chan-sccp/chan-sccp)

**Comment by rofferman** [comment]
Ok I will... One last silly ? 
Where is the debug log at? It is on

**Comment by dkgroot** [comment]
It should be printing to /var/log/apache2/acces.log / /var/log/apache2/error.log (check the /var/log/apache2 directory, log file could have a different name).

**Comment by rofferman** [comment]
So I think I have this working but, Im sure you could clean up my mapping.

I excluded List.xml from the rewrite sort of by editing the tftpboot.conf file

I had to had tftpboot to the path in the List.xml files to make it map correctly

I will attach my files with the changes and see what you think. I am not much of programmer lol

index.cnf
```
[main]
debug = on ; The output in the browser window for more information
tftproot = /tftpboot
default_language = English_United_States

firmware = firmware
settings = /tftpboot
wallpapers = Desktops
ringtones = ringtones
locales = locales
countries = countries
languages = /tftpboot/languages
log = /tftpboot/provision.log
```
tftpboot.conf
```
Listen 6970
<VirtualHost *:6970>
    DocumentRoot "/tftpboot"
    ErrorLog /var/log/httpd/tftp.error.log
    CustomLog /var/log/httpd/tftp.access.log combined

    <Directory /tftpboot>
      Options FollowSymlinks
      AllowOverride none
      Require all granted
      RewriteEngine on
      RewriteBase "/"
	  RewriteCond "/tftpboot/%{REQUEST_URI}" !List.xml$
      RewriteCond "/tftpboot/%{REQUEST_FILENAME}" !-f
      RewriteCond "/tftpboot/%{REQUEST_FILENAME}" !-d
	  RewriteRule "(.*)" "index.php?id=$1" [PT,QSA]
    </Directory>

    <Directory />
        Options FollowSymLinks
        AllowOverride all
        Require all granted
    </Directory>

    <Location />
      Require all granted
    </Location>

    Alias / "/tftpboot/"
</VirtualHost>
```

List.xml

```
CiscoIPPhoneImageList>
<!--
Used By: 7970
Image = Thumbnail (size 80x53x12 color png format)
URL = Backgroup (size 320x216x16 color png format)

Example:
	<ImageItem Image="TFTP:320x216x16/TN-Fountain.png" URL="TFTP:320x212x16/Fountain.png"/> 
	<ImageItem Image="TFTP:320x216x16/TN-FullMoon.png" URL="TFTP:Desktops/320x212x16/FullMoon.png"/> 
-->
	<ImageItem Image="TFTP:tftpboot/Desktops/320x216x16/Chan-SCCP-b_thumb.png" URL="TFTP:tftpboot/Desktops/320x216x16/Chan-SCCP-b.png"/>
	<ImageItem Image="TFTP:tftpboot/Desktops/320x216x16/Wolfes-Logo-tn.png"  URL="TFTP:tftpboot/Desktops/320x216x16/Wolfes-Logo.png"/>
</CiscoIPPhoneImageList>
```

**Comment by dkgroot** [comment]
@rofferman

I see you found a bit of a workaround by excluding List.xml from being redirected to the index.php and changing the path. I guess that works. but it is not really a solution to the problem :-) Congrats !

FYI: You can also use HTTP instead of TFTP in the List.xml. which would work as well. And should  be faster, because tftp is pretty slow.

The real solution would be to get rid of index.php completely and reformat rewrite.rules so that it can be used for multiple web/tftp servers.

**Comment by rofferman** [comment]
I agree, but like I said I am not a programmer, so yes this is a crude workaround

**Comment by PhantomVl** [comment]
I Fix wallpapers bug.

**Comment by dkgroot** [comment]
@rofferman Can you retrieve the latest provision_sccp version and check, so we can close this issue ? (You should remove you temporary fix while testing of course :-) )

**Comment by rofferman** [comment]
works perfect.
Thank you

**Comment by dkgroot** [comment]
Thanks @rofferman for reporting back
Thanks @PhantomVl for fixing the issue !
